title: winxpnara_blog
description: "
もうなにもかも 忘れて\n
\n
今宵は シルエットダンス\n
\n
知らない 要らない 全然\n
\n
なんの法則もなく\n
\n
ただ舞って舞う\n
"
author: winxp
url: "https://blog.winxpnara.com" # 替换为您的GitHub Pages URL
baseurl: ""

# 构建设置
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 时区和语言设置
timezone: Asia/Shanghai
lang: zh-CN